name: Build Combined List
# This workflow is triggered on pushes to the repository.
workflow_dispatch:
    inputs:
      run:
        description: 'just a thing'
        required: false

jobs:
    build_list:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2 # Checkout the repository
        - run: |
            cd ..
            chmod +x SecListsCombined/build.sh
            ./SecListsCombined/build.sh       
        - run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -m "[Auto] update combined list" -a
        - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'main'
            directory: .
        