name: Build Combined List
on: push

jobs:
    build_list:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2 # Checkout the repository
        - run: |
            cd ..
            chmod +x SecListsCombined/build.sh
            ./SecListsCombined/build.sh   
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_KEY }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET }}
            export AWS_DEFAULT_REGION=us-east-2
            aws s3 cp ./SecListsCombined/PASSWORDS.zip s3://cbrqmain/PASSWORDS.zip