name: Build Combined List
on: push

jobs:
    build_list:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2 # Checkout the repository
        - run: |
            apt update && apt upgrade -y && apt install -y binutils
            cd ..
            chmod +x SecListsCombined/build.sh
            ./SecListsCombined/build.sh       
        - run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add *
            git commit -ma "[Auto] update combined list"
        - uses: ad-m/github-push-action@v0.6.0
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: 'main'        